name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy-owlbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Connect to server and update code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.OWLBOT_SERVER_IP }}"
          username: "${{ secrets.OWLBOT_SERVER_USER }}"
          script: |
            git pull origin master

      - name: Restart service
        run: |
          sudo systemctl restart "${{ secrets.OWLBOT_SERVICE_NAME }}"
